
curl -H "Accept: application/json" http://my-client-with-secret:secret@localhost:8080/oauth/token -d grant_type=client_credentials

###

curl -H "Authorization: Bearer a058fbec-3b05-4156-a8b1-2c08fff78b36" http://localhost:8080/hello

###

POST http://my-client-with-secret:secret@localhost:8080/oauth/token?grant_type=client_credentials HTTP/1.1
Accept: application/json

grant_type=client_credentials

###

GET http://localhost:8080/hello HTTP/1.1
Authorization: Bearer be0246b6-ab69-44fb-9ba0-8ada625d56c5



#### fibonacci Server
POST http://my-client-with-secret:secret@localhost:8080/oauth/token?grant_type=client_credentials HTTP/1.1
Accept: application/json

###

GET http://localhost:8080/increment HTTP/1.1
Authorization: Bearer 43e511cc-a764-4893-a5fb-9a3c8e1236a3

###

DELETE http://localhost:8080/reset HTTP/1.1
Authorization: Bearer 13813ab4-5367-4526-8d33-2f70b22499f5